name: 2 - Develop

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths-ignore:
      - "docs/**"
  pull_request:
    branches:
      - develop

  jobs: 
  shared-job: 
    uses: .github/workflows/2-reusable-develop.yml

