name: 8 - Rollback

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Ambiente (develop|production)"
        required: true
        default: "develop"
      version:
        description: "Versão/tag para rollback (ex: v1.2.3)"
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Rollback (placeholder)
        run: |
          echo "Rollback no ambiente: ${{ inputs.target }}"
          echo "Voltando para versão: ${{ inputs.version }}"
